GET http://localhost:3001/todos

###
POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text" : "new todo 2",
    "dueDate": "30.08.2023",
    "description": "Here goes the description",
    "completed":true
}

###

DELETE http://localhost:3001/todo/delete/64ed0bfa9da50374fe2b2689

###

POST http://localhost:3001/auth/user/login
Content-Type: application/json

{
  
    "email": "emaila@abcd.def",
    "password": "PASSWORD"
}

###

POST http://localhost:3001/auth/user/signup
Content-Type: application/json

{
    "email": "emailaaa@dasdasd",
    "password": "PASSWORD",
    "firstName":"asdsad",
    "lastName": "sdasdasd"
}

